import Head from 'next/head'
import { Inter } from '@next/font/google'
import Hero from '@/components/Hero'
import Header from '@/components/Header'
import Features from '@/components/Features'
import Footer from '@/components/Footer'
import CTA from '@/components/CTA'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Fina-mint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/finamintIcon.ico" />
      </Head>

      <Header />

      <Hero />
      
      <CTA />

      <Features />

      <Footer />

    </>
  )
}
